name: CI/CD for Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Naver Cloud Registry
      run: |
        docker login ${{ secrets.NCP_REGISTRY_SERVER }} -u "${{ secrets.NCP_ACCESSKEY }}" --password-stdin <<< "${{ secrets.NCP_REGISTRY_PASSWORD }}"

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.NCP_REGISTRY_SERVER }}/springboot-app:latest .
        docker push ${{ secrets.NCP_REGISTRY_SERVER }}/springboot-app:latest

    - name: Configure kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Apply kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENTS }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/spring-boot-app \
          spring-boot-app=${{ secrets.NCP_REGISTRY_SERVER }}/springboot-app:latest
